AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  redirect-app-ts

  Sample SAM Template for redirect-app-ts
  
Globals:
  Function:
    Timeout: 100
    MemorySize: 128

Resources:
  RedirectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: redirect/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Events:
        redirect:
          Type: Api
          Properties:
            Path: /redirect
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Target: "es2020"
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RedirectApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RedirectFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RedirectFunction.Arn
  RedirectFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt RedirectFunctionRole.Arn
